/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package wida.reader;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**   <color name="white">#E8E8D0</color> 
         */
        public static final int TextViewColor=0x7f040000;
    }
    public static final class dimen {
        public static final int bottom_tab_font_size=0x7f050002;
        public static final int bottom_tab_padding_drawable=0x7f050000;
        public static final int bottom_tab_padding_up=0x7f050001;
    }
    public static final class drawable {
        public static final int back_left=0x7f020000;
        public static final int back_right=0x7f020001;
        public static final int bookshelf=0x7f020002;
        public static final int bookshelf_addbook=0x7f020003;
        public static final int bookshelf_bg=0x7f020004;
        public static final int bookshelf_reflash=0x7f020005;
        public static final int bookshelf_setting=0x7f020006;
        public static final int brightness_dark=0x7f020007;
        public static final int brightness_light=0x7f020008;
        public static final int checkbox_empty=0x7f020009;
        public static final int checkbox_ok=0x7f02000a;
        public static final int clogo=0x7f02000b;
        public static final int corners_bg=0x7f02000c;
        public static final int cover_txt=0x7f02000d;
        public static final int filechooser_folder=0x7f02000e;
        public static final int filechooser_goback=0x7f02000f;
        public static final int filechooser_parentfloder=0x7f020010;
        public static final int filechooser_scaner=0x7f020011;
        public static final int filechooser_txt=0x7f020012;
        public static final int home_btn_bg=0x7f020013;
        public static final int home_btn_bg_d=0x7f020014;
        public static final int home_btn_bg_n=0x7f020015;
        public static final int home_btn_bg_s=0x7f020016;
        public static final int home_setting=0x7f020017;
        public static final int ic_launcher=0x7f020018;
        public static final int icon_1_n=0x7f020019;
        public static final int icon_2_n=0x7f02001a;
        public static final int icon_3_n=0x7f02001b;
        public static final int icon_4_n=0x7f02001c;
        public static final int icon_5_n=0x7f02001d;
        public static final int maintab_toolbar_bg=0x7f02001e;
        public static final int menu_go=0x7f02001f;
        public static final int menu_goback=0x7f020020;
        public static final int menu_light=0x7f020021;
        public static final int menu_menu=0x7f020022;
        public static final int menu_select=0x7f020023;
        public static final int menu_select_down=0x7f020024;
        public static final int menu_selectitem=0x7f020025;
        public static final int menu_setting=0x7f020026;
        public static final int menu_sign=0x7f020027;
        public static final int menu_size=0x7f020028;
        public static final int my_drawable=0x7f020029;
        public static final int playback_seekbar_style=0x7f02002a;
        public static final int playback_seekbar_thumb=0x7f02002b;
        public static final int power0=0x7f02002c;
        public static final int power1=0x7f02002d;
        public static final int power2=0x7f02002e;
        public static final int power3=0x7f02002f;
        public static final int power4=0x7f020030;
        public static final int progressbar_first=0x7f020031;
        public static final int progressbar_outline=0x7f020032;
        public static final int progressbar_second=0x7f020033;
        public static final int reader_switch_off=0x7f020034;
        public static final int reader_switch_on=0x7f020035;
        public static final int reader_tool_fontsize=0x7f020036;
        public static final int reader_tool_light=0x7f020037;
        public static final int reader_tool_progress=0x7f020038;
        public static final int reader_tool_size_down=0x7f020039;
        public static final int reader_tool_size_up=0x7f02003a;
        public static final int readerbackground=0x7f02003b;
        public static final int scroll_point_dark=0x7f02003c;
        public static final int scroll_point_light=0x7f02003d;
        public static final int shelves_editbook=0x7f02003e;
        public static final int shelves_editbook_d=0x7f02003f;
        public static final int thumb_dn=0x7f020040;
        public static final int thumb_up=0x7f020041;
        public static final int titlebar_big=0x7f020042;
        public static final int toggle_button=0x7f020043;
        public static final int tool11=0x7f020044;
        public static final int tool22=0x7f020045;
        public static final int tool33=0x7f020046;
        public static final int tool44=0x7f020047;
        public static final int transparent=0x7f020048;
    }
    public static final class id {
        public static final int Battery=0x7f080011;
        public static final int ImageButton01=0x7f080048;
        public static final int ImageButton02=0x7f080049;
        public static final int ImageButton03=0x7f08004a;
        public static final int Page3D=0x7f08000e;
        public static final int PageFilp=0x7f080014;
        public static final int RelativeLayout_Item=0x7f08003e;
        public static final int ScrollLayoutTest=0x7f08001d;
        public static final int alllayout=0x7f08000a;
        public static final int appstate=0x7f08000f;
        public static final int array_button=0x7f080024;
        public static final int array_image=0x7f080018;
        public static final int array_text=0x7f080026;
        public static final int array_title=0x7f080025;
        public static final int bookName=0x7f080012;
        public static final int book_catalogue_list=0x7f080000;
        public static final int book_select=0x7f080027;
        public static final int bookmark_createtime=0x7f08001a;
        public static final int bookmark_list=0x7f080016;
        public static final int bookmark_percent=0x7f080019;
        public static final int bookmark_string=0x7f080017;
        public static final int bookshelf_linearLayout=0x7f08001b;
        public static final int bookview=0x7f08002d;
        public static final int btAddBook=0x7f080030;
        public static final int btExit=0x7f08002f;
        public static final int btnScan=0x7f08002a;
        public static final int btn_import=0x7f080035;
        public static final int btn_leftTop=0x7f080033;
        public static final int build_catalogue_button=0x7f080003;
        public static final int catalogue_bookname=0x7f080005;
        public static final int catalogue_goback=0x7f080004;
        public static final int catalogue_name=0x7f080009;
        public static final int filechooser_goback=0x7f080028;
        public static final int gvmenu=0x7f08003b;
        public static final int gvmenu2=0x7f08003c;
        public static final int header=0x7f08001c;
        public static final int hr_line=0x7f080015;
        public static final int imageButton1=0x7f080046;
        public static final int imageView1=0x7f08003d;
        public static final int imageView2=0x7f08004c;
        public static final int imgBackFolder=0x7f08002c;
        public static final int imgStopScan=0x7f080031;
        public static final int imgdetail=0x7f08000c;
        public static final int imglayout=0x7f08000b;
        public static final int item_image=0x7f08003f;
        public static final int linearlayout=0x7f08001f;
        public static final int longClickMenu=0x7f080020;
        public static final int long_click_bookname=0x7f080021;
        public static final int long_click_delete=0x7f080023;
        public static final int long_click_link=0x7f080022;
        public static final int main_tab=0x7f080006;
        public static final int menu_goback=0x7f08003a;
        public static final int menu_relativeLayout=0x7f080039;
        public static final int neight_mode_button=0x7f08004b;
        public static final int nowTime=0x7f080010;
        public static final int operateLinear=0x7f080032;
        public static final int pageControl=0x7f08001e;
        public static final int percent=0x7f080013;
        public static final int radio_button0=0x7f080007;
        public static final int radio_button1=0x7f080008;
        public static final int radio_button2=0x7f080036;
        public static final int radio_button3=0x7f080037;
        public static final int reader_tool_size_down=0x7f080041;
        public static final int reader_tool_size_up=0x7f080042;
        public static final int search_webview=0x7f080038;
        public static final int textView1=0x7f080002;
        public static final int textView2=0x7f080047;
        public static final int tool11=0x7f080040;
        public static final int tool22=0x7f080043;
        public static final int tool44=0x7f08004d;
        public static final int tool_progress_book_name=0x7f08004e;
        public static final int tool_progress_light=0x7f080045;
        public static final int tool_progress_percent=0x7f08004f;
        public static final int tool_progress_seekbar=0x7f080050;
        public static final int tuaninfo=0x7f08000d;
        public static final int tvEmptyCatelogue=0x7f080001;
        public static final int tvEmptyHint=0x7f08002e;
        public static final int tvPath=0x7f08002b;
        public static final int tvTitle=0x7f080029;
        public static final int tv_head=0x7f080034;
        public static final int use_system_light_button=0x7f080044;
    }
    public static final class layout {
        public static final int book_catalogue=0x7f030000;
        public static final int book_catalogue_activity=0x7f030001;
        public static final int book_catalogue_item=0x7f030002;
        public static final int book_item=0x7f030003;
        public static final int book_reader_3d=0x7f030004;
        public static final int book_reader_flip=0x7f030005;
        public static final int bookmark=0x7f030006;
        public static final int bookmark_item=0x7f030007;
        public static final int bookshelf_activity=0x7f030008;
        public static final int bookshelf_longclick_menu=0x7f030009;
        public static final int filechooser_bookitem=0x7f03000a;
        public static final int filechooser_fileshow=0x7f03000b;
        public static final int filescan_fileshow=0x7f03000c;
        public static final int header=0x7f03000d;
        public static final int main_activity=0x7f03000e;
        public static final int main_search=0x7f03000f;
        public static final int reader_gridview_menu=0x7f030010;
        public static final int reader_menu_item=0x7f030011;
        public static final int reader_tool_fontsize=0x7f030012;
        public static final int reader_tool_light=0x7f030013;
        public static final int reader_tool_progress=0x7f030014;
    }
    public static final class string {
        public static final int add_book=0x7f060003;
        public static final int app_name=0x7f060000;
        public static final int book_catalogue=0x7f06000e;
        public static final int bookmark=0x7f06000f;
        /**  start 文件选择器  
         */
        public static final int empty_hint=0x7f06000a;
        public static final int go_back=0x7f060001;
        public static final int inset_book_failed=0x7f06000d;
        public static final int main_bookshelf=0x7f060006;
        public static final int main_home=0x7f060004;
        public static final int main_search=0x7f060005;
        public static final int main_setting=0x7f060007;
        public static final int menu_setting=0x7f060008;
        public static final int more=0x7f060009;
        public static final int my_bookshelf=0x7f060002;
        public static final int open_file_error_format=0x7f06000c;
        public static final int sdcard_unmonted_hint=0x7f06000b;
    }
    public static final class style {
        public static final int MyCheckBox=0x7f070005;
        /**  全屏幕拉伸
         */
        public static final int layout_full=0x7f070001;
        /**  横向分布
         */
        public static final int layout_horizontal=0x7f070003;
        /**  纵向分布
         */
        public static final int layout_vertical=0x7f070004;
        /**  固定自身大小
         */
        public static final int layout_wrap=0x7f070002;
        public static final int main_tab_bottom=0x7f070000;
    }
}
